In [1]:
import pandas as pd
import numpy as np

DATA_PATH = "../data/raw/SHED 2025 CSV Raw.csv"

df = pd.read_csv(DATA_PATH)

C:\Users\adang\AppData\Local\Temp\ipykernel_25988\3775693411.py:6: DtypeWarning: Columns (111: GH14, 422: ppfs1460, 423: ppfs1461, 424: ppfs1462, 425: ppfs1463, 426: ppfs1613, 427: ppfs1464, 428: ppfs0549, 429: ppfs1493, 430: ppfs2342, 431: ppfs2309, 432: ppfs2340, 433: ppfs2343, 434: ppfs2344, 435: ppfs2345) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DATA_PATH)

In [2]:
df.shape

(12934, 815)

In [3]:
df.head()

,shedid,duration,weight,weight_pop,panel_weight,panel_weight_pop,xlaptop,L0_a,L0_b,L0_c,...,E12_g_iflag,CH2A_iflag,race_5cat,inc_4cat_50k,educ_4cat,pay_casheqv,atleast_okay,control,malefemale,year
0,202304484,1922,0.6467,13225.3400,NaN,NaN,No,Yes,No,No,...,0,0,White,"$50,000–$99,999",Some college/technical or associates degree,Yes,Yes,Public,Male,2025
1,202204577,189270,0.9687,19810.3406,0.9357,56011.816,No,No,No,No,...,0,0,White,"$100,000 or more",Bachelor's degree or more,Yes,Yes,Public,Female,2025
2,202301342,4240,1.0129,20715.6590,NaN,NaN,No,No,No,Yes,...,0,0,White,"$50,000–$99,999",Less than a high school degree,No,No,NaN,Female,2025
3,202500830,591,1.0278,21020.6151,NaN,NaN,No,Yes,No,No,...,0,0,White,"$50,000–$99,999",High school degree or GED,Yes,Yes,NaN,Male,2025
4,202504363,2508,0.7688,15722.4241,NaN,NaN,No,Yes,No,No,...,0,0,White,"$50,000–$99,999",Some college/technical or associates degree,Yes,Yes,Public,Female,2025

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12934 entries, 0 to 12933
Columns: 815 entries, shedid to year
dtypes: float64(19), int64(370), object(1), str(425)
memory usage: 80.4+ MB

In [5]:
df[["shedid", "weight", "weight_pop"]].head()

      shedid  weight  weight_pop
0  202304484  0.6467  13225.3400
1  202204577  0.9687  19810.3406
2  202301342  1.0129  20715.6590
3  202500830  1.0278  21020.6151
4  202504363  0.7688  15722.4241

In [6]:
df[["weight", "weight_pop"]].describe()

             weight    weight_pop
count  12934.000000  12934.000000
mean       0.999999  20451.455468
std        0.379342   7758.099154
min        0.331900   6788.330300
25%        0.750300  15344.733300
50%        0.924500  18906.865400
75%        1.166800  23862.983700
max        3.488200  71339.356900

In [7]:
df["shedid"].nunique()

12934

In [8]:
df["shedid"].duplicated().sum()

np.int64(0)

In [9]:
df.dtypes.value_counts()

str        425
int64      370
float64     19
object       1
Name: count, dtype: int64

In [10]:
df["B2"].value_counts(dropna=False)

B2
Doing okay                        5005
Living comfortably                4479
Just getting by                   2387
Finding it difficult to get by    1063
Name: count, dtype: int64

In [11]:
ef3_cols = [
    "EF3_a",
    "EF3_b",
    "EF3_c",
    "EF3_d",
    "EF3_e",
    "EF3_f",
    "EF3_g",
    "EF3_h"
]

for col in ef3_cols:
    print("\n", col)
    print(df[col].value_counts(dropna=False))

 EF3_a
EF3_a
No     7797
Yes    5137
Name: count, dtype: int64

 EF3_b
EF3_b
No     10998
Yes     1936
Name: count, dtype: int64

 EF3_c
EF3_c
No     7328
Yes    5606
Name: count, dtype: int64

 EF3_d
EF3_d
No     12572
Yes      362
Name: count, dtype: int64

 EF3_e
EF3_e
No     11745
Yes     1189
Name: count, dtype: int64

 EF3_f
EF3_f
No     12662
Yes      272
Name: count, dtype: int64

 EF3_g
EF3_g
No     12108
Yes      826
Name: count, dtype: int64

 EF3_h
EF3_h
No     11404
Yes     1530
Name: count, dtype: int64